version: '3'
services:
# fluent에서 pubsub로 전송을 위해 fluent-plugin-gcloud-pubsub-custom 설치가 필요하여 Dockerfile로 이미지를 빌드
  fluent:
    build:
      context: ./fluent #Dockerfile이 있는 위치
      dockerfile: Dockerfile
    ports:
      - 24224:24224
    volumes:
      - ./fluent/fluent.conf:/fluentd/etc/fluent.conf #fluent.conf를 컨테이너 안으로 복사
      - ./key/google-service-key.json:/tmp/google-service-key.json #pubsub 연결에 사용할 서비스 키를 컨테이너 안으로 복사. fluentd.conf에서 사용
    container_name: c_fluent #컨테이너 이름
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: c_nginx
    logging: # nginx 의 모든 로그를 fluent로 출력
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224 # fluentd IP로 로컬에서 수행하므로 127.0.0.1로 지정
        tag: logtest # fluent로 전송시 tag
    depends_on:
      - fluent # fluent 컨테이너와의 의존성을 명시
  dataprocessing:
    build:
      context: ./ #Dockerfile이 있는 위치
      dockerfile: ./apache-beam/Dockerfile
    container_name: c_dataprocessing
