version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: dataPipeline_web
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: sample
    depends_on:
      - fluentd
  fluentd:
    image: fluent/fluentd:edge-debian
    ports:
      - 24224:24224
    volumes:
      - ./fluent/fluent.conf:/fluentd/etc/fluent.conf
    container_name: dataPipeline_fluentd
